#!/bin/bash
set -euo pipefail

release_type=$1

echo "Pulling latest"
git pull

echo"Bumping version"
npm version "$release_type" -m "Release %s"

echo"Pushing"
git push --set-upstream origin master
git push --tags

echo "Done"
